### ISSUE TITLE
Unable to add `textStyleId` to JSX <Text /> node

### ISSUE THREAD

**Issue by DavidQL** [figma/widget-typings#25]
I'm drawing to the Figma canvas using the new [figma.createNodeFromJSXAsync](https://www.figma.com/plugin-docs/api/properties/figma-createnodefromjsxasync) API. 

I'm trying to use `Text` from `figma.widget` like this. However, the `<Text />` component does not accept any props that apply a local text style. 

```
const { Text } = figma.widget;

export default function TextComponent() {

  return (
    <Text 
        textStyleId="26fab46e809d354dbf7bc4ed3b0b0b3090813203" >
        // ^^^ this doesn't work. No props for `textStyleId`

       Here is some text

    </Text>
  )
}
```

In the old imperative way of doing this, I could apply it like this:
```
  const text = figma.createText();
  text.textStyleId = "<style ID goes here>"
```

How can I accomplish the same thing using the declarative JSX syntax?

**Comment by SawyerHood** [comment]
I'm sorry but `<Text />` doesn't support style ids and we don't have a plan to support it at the moment we are only trying to support properties that are directly usable by widgets.

You can use `createNodeFromJSXAsync` and then manually set the textStyleId imperatively afterwards if that helps!
