### ISSUE TITLE
JSX Component Error after Installing React and Related Libraries

### ISSUE THREAD

**Issue by mikhin** [figma/widget-typings#38]
I am currently working on a Figma widget boilerplate project that uses the following configuration:

```json
{
  "jsxFactory": "figma.widget.h",
  "jsxFragmentFactory": "figma.widget.Fragment"
}
```

This project does not use React. However, after installing `react`, `react-dom`, `@types/react`, and `@types/react-dom`, I encountered a TypeScript error when trying to use a custom component as a JSX component.

The error message is as follows:

```
TS2786: 'BoardComponent' cannot be used as a JSX component.
Its type '({ backgroundColor, }: { backgroundColor: string; }) => FigmaDeclarativeNode' is not a valid JSX element type.
Type '({ backgroundColor, }: { backgroundColor: string; }) => FigmaDeclarativeNode' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
Type 'FigmaDeclarativeNode' is not assignable to type 'ReactNode'.
Type 'FigmaVirtualNode<any>' is not assignable to type 'ReactNode'.
```

The `BoardComponent` is defined as follows:

```typescript
import { BoardComponent } from './components/Board.tsx';
...
return <BoardComponent backgroundColor={backgroundColor} />;
```

It seems that the type `FigmaDeclarativeNode` is not compatible with `ReactNode`, which is causing the issue. I would appreciate any guidance on how to resolve this error.

**Comment by jefflee-figma** [comment]
It's possible your TypeScript config is choosing to use the React type definitions when it encounters JSX expressions. Figma widget JSX is not the same thing as React JSX, but if you install the React type libraries, TypeScript may get confused.

**Comment by elainefigma** [comment]
Based on Jeff's response above, I'm resolving this issue - please feel free to follow-up if you have any additional questions.
